version: '3.8'

services:
  king-7:
    image: david-7
    build: .
    ports:
      - '6001:4000'
    environment:
      - MONGODB_URI:'mongodb://localhost:27017/salesreport'   
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
